[build]
  command = "npm install"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["views/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
